### PR TITLE
Don't assign -1 to unsigned types

### PR DESCRIPTION
**Pull request by madeso**
`std::string::size_type` is unsigned and can't hold negative numbers, `std::string::npos` seems like a better choice here

### CODE REVIEW

**Comment by madeso** [comment]
ubuntu 16.04 has been removed, that's why it's failing
https://github.com/actions/virtual-environments/issues/3287

**Comment by kainjow** [comment]
Makes sense. Did this show up as a compiler warning/error?

**Comment by madeso** [comment]
Yes. Not sure what the actual comandline argument was that casues it, I would guess it comes from -Wconversion but could also come from Wall or Wextra.

**Comment by kainjow** [comment]
Yes I see it with -Wconversion. Going to add that for the tests target. Surprised that hasn't come up before.

**Comment by kainjow** [comment]
@madeso I fixed the Ubuntu issue. Can you merge master?

**Comment by madeso** [comment]
Done. Both appveyor and gh actions are waiting for approval.

**Pull request merged**
